# Molecule managed

{% if item.registry is defined %}
FROM {{ item.registry.url }}/{{ item.image }}
{% else %}
FROM {{ item.image }}
{% endif %}

RUN if [ $(command -v dnf) ]; then \
            dnf makecache && dnf -y install python3 python3-devel python3-dnf && dnf clean all; \
    elif [ $(command -v yum) ]; then \
        yum makecache fast && yum install -y python yum-plugin-ovl && sed -i 's/plugins=0/plugins=1/g' /etc/yum.conf && yum clean all; \
    fi
